import pandas as pd
import io
import os
from datetime import datetime


def export_csv(df: pd.DataFrame, output_path: str) -> str:
    """Export cleaned dataframe to CSV."""
    df.to_csv(output_path, index=False, encoding="utf-8-sig")
    return output_path


def export_excel(df: pd.DataFrame, output_path: str) -> str:
    """Export cleaned dataframe to Excel."""
    df.to_excel(output_path, index=False, engine="xlsxwriter")
    return output_path


def export_python_code(code: str, audit_log: list, output_path: str) -> str:
    """Export the cleaning code as a standalone Python script."""
    header = f"""# ============================================================
# كود تنظيف البيانات — مولّد تلقائياً بواسطة DataCleaner AI
# تاريخ التوليد: {datetime.now().strftime('%Y-%m-%d %H:%M')}
# ============================================================

import pandas as pd
import numpy as np

# --- تحميل البيانات ---
# قم بتغيير المسار إلى مسار ملفك الفعلي
df = pd.read_csv("your_file.csv", encoding="utf-8-sig")

# --- خطوات التنظيف ---
"""
    footer = f"""

# --- حفظ النتيجة ---
df.to_csv("cleaned_output.csv", index=False, encoding="utf-8-sig")
print("✅ تم تنظيف البيانات وحفظها بنجاح!")
print(f"عدد الصفوف النهائي: {{len(df)}}")
"""
    full_code = header + code + footer

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_code)

    return output_path


def export_pdf_report(
    audit_log: list,
    scan_report: dict,
    rows_before: int,
    rows_after: int,
    output_path: str
) -> str:
    """Generate a professional PDF cleaning report in Arabic."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_fill_color(30, 30, 50)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 15, "DataCleaner AI - Cleaning Report", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Summary Section
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 255)
    pdf.cell(0, 10, "Summary", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Rows Before Cleaning: {rows_before}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Rows After Cleaning:  {rows_after}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Rows Removed:         {rows_before - rows_after}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Issues Found
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 255)
    pdf.cell(0, 10, "Issues Detected (Before Cleaning)", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if scan_report.get("issues"):
        for issue in scan_report["issues"]:
            msg = issue.get("message", "")
            # Write as ASCII-safe for PDF
            safe_msg = msg.encode("ascii", "replace").decode("ascii")
            pdf.multi_cell(0, 7, f"  - {safe_msg}")
    else:
        pdf.cell(0, 8, "  No major issues detected.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Audit Log
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(240, 240, 255)
    pdf.cell(0, 10, "Changes Applied (Audit Log)", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if audit_log:
        for i, entry in enumerate(audit_log, 1):
            action = entry.get("action", "").encode("ascii", "replace").decode("ascii")
            detail = entry.get("detail", "").encode("ascii", "replace").decode("ascii")
            impact = entry.get("impact", "").encode("ascii", "replace").decode("ascii")
            pdf.multi_cell(0, 7, f"  {i}. [{action}] {detail} {impact}")
    else:
        pdf.cell(0, 8, "  No changes logged.", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, "Generated by DataCleaner AI - Your Private Data Assistant", align="C")

    pdf.output(output_path)
    return output_path

def export_jupyter_notebook(code: str, audit_log: list, output_path: str) -> str:
    """Export the cleaning code as a Jupyter Notebook (.ipynb)."""
    import json
    from datetime import datetime

    cells = []
    
    # Header Markdown Cell
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🚀 DataCleaner AI - Jupyter Notebook\n",
            f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
            "---\n",
            "This notebook contains the automated cleaning steps generated by DataCleaner AI."
        ]
    })

    # Initial Setup Code Cell
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import pandas as pd\n",
            "import numpy as np\n",
            "\n",
            "# Load your data here\n",
            "df = pd.read_csv('your_file.csv', encoding='utf-8-sig')\n",
            "df.head()"
        ]
    })

    # If there's cleaning code, we can split it by requests or just put it all in one cell.
    # To make it nice, we'll put all the code generated by AI in one block for now.
    if code.strip():
        # Add markdown explanation
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 🧹 Cleaning Operations\n", "Applying the AI-generated python commands."]
        })
        
        # Format the code string into a list of lines with newline characters
        code_lines = [line + '\n' for line in code.split('\n')]
        
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": code_lines
        })

    # Save Output Code Cell
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Save the cleaned dataframe\n",
            "df.to_csv('cleaned_output.csv', index=False, encoding='utf-8-sig')\n",
            "print('✅ Data successfully cleaned and saved!')"
        ]
    })

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)

    return output_path
